### ISSUE TITLE
The Bus stops and bus goes while there is no point of entry because of the bus is locked help me please?

### ISSUE THREAD

**Issue by harshit2121** [FedericoDeBona/publictransport#11]
The Bus everytime stops we try to enter with 'F' keybind or 'G' but the bus is lock and we cannot enter give me solution.
Extra: Framework im useing is QB-Core.

**Comment by FedericoDeBona** [comment]
Hi, if you are using `qb-vehiclekeys` add to the `Config.NoLockVehicles` array all the hash you are using. Example:
```LUA
Config.NoLockVehicles = {
'bus',
}
```
If you don't find it in `qb-vehiclekeys`, it might be in `qb-doorlock`, I'm not sure

**Comment by harshit2121** [comment]
Thankyou its Solved!
