### ISSUE TITLE
route issue

### ISSUE THREAD

**Issue by nyj1911** [FedericoDeBona/publictransport#2]
bus station 6th and above, bus starting wrong routing and AI don't know what to do

**Comment by FedericoDeBona** [comment]
> 
> 
> bus station 6th and above, bus starting wrong routing and AI don't know what to do

I've just uploaded a reviewd version. Can you please see if you are still having this issue?

**Comment by IOxeOfficial** [comment]
I have tried the new version this morning and I have added the new old points modified for the new version and from point 6 of the bus stop it continues to enter the rest including the sixth and starts the route again
